FROM --platform=linux/amd64 ubuntu:20.04 AS builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git python3 python3-pip

COPY . /repo
WORKDIR /repo
RUN make -j8 PYTHON=python3
RUN chmod +x bin/espruino

FROM ubuntu:20.04 AS package
COPY --from=builder /repo/bin/espruino /
